import { dir } from "i18next";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { languages } from '../i18n/settings'

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}
const poppins = Poppins({
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lng } }: any) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head />
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
